#!/usr/bin/env node
// Reviewer sign-off packet: one page per drafted module (claims, sources, open TODOs, blank
// signature block). Read-only over content/. It never sets `approved` and never fills a signature.
import fs from 'node:fs';
import path from 'node:path';
import { loadAll, ROOT } from './lib/content.js';

const UNRESOLVED = /consensus\.app|pubmed\.ncbi\.nlm\.nih\.gov\/\?term=/;

export function collectTodos(node, trail = '', out = []) {
  if (typeof node === 'string') { if (/\bTODO\b/.test(node)) out.push({ where: trail, text: node }); }
  else if (Array.isArray(node)) node.forEach((v, i) => collectTodos(v, `${trail}[${i + 1}]`, out));
  else if (node && typeof node === 'object') for (const [k, v] of Object.entries(node)) collectTodos(v, trail ? `${trail}.${k}` : k, out);
  return out;
}

export const sourceState = url => (UNRESOLVED.test(url) ? 'UNRESOLVED (search link)' : 'record link');

export function modulePage(m) {
  const L = [];
  L.push(`# ${m.title}`, '', `Module id: \`${m.id}\`  |  Domain: ${m.domain}  |  Status: **${m.status}**  |  Kind: ${m.kind || 'clinical'}`, '');
  L.push('> DRAFT for review. Nothing here is approved. Do not use for patient care.', '');
  L.push('## Why this matters', '', m.why_this_matters || 'not written', '');
  if (m.what_changes_from_human?.length) {
    L.push('## Claims that differ from human practice', '');
    m.what_changes_from_human.forEach(c => L.push(`- ${c.point}`));
    L.push('');
  }
  for (const k of ['recognition', 'management']) {
    const items = m.content?.[k] || [];
    if (items.length) { L.push(`## ${k[0].toUpperCase() + k.slice(1)}`, ''); items.forEach(t => L.push(`- ${t}`)); L.push(''); }
  }
  if (m.compare?.length) {
    L.push('## Dog vs human compare rows', '');
    m.compare.forEach(r => L.push(`- **${r.topic}** (human basis: ${r.human_basis}): human: ${r.human} | canine: ${r.canine}`));
    L.push('');
  }
  L.push('## Sources', '', '| # | Citation | Link status |', '|---|----------|-------------|');
  (m.sources || []).forEach((s, i) => L.push(`| ${i + 1} | ${s.citation.replace(/\|/g, '/')} | ${sourceState(s.url)} (${s.url}) |`));
  L.push('');
  const todos = collectTodos(m);
  L.push(`## Open items (${todos.length})`, '');
  if (todos.length) todos.forEach(t => L.push(`- [ ] \`${t.where}\`: ${t.text}`)); else L.push('None recorded.');
  L.push('', '## Reviewer decisions', '', 'Approve / approve with changes / reject: ____________', '', 'Comments:', '', '');
  L.push('## Sign-off', '', '| Role | Name | Credential | Date | Signature |', '|------|------|------------|------|-----------|', '| Veterinarian | | | | |', '| Physician | | | | |', '');
  L.push('Approval requires both signatures, no open TODO, and every source resolved to a record link.');
  return L.join('\n') + '\n';
}

export function buildPackets(outDir, { modules } = loadAll()) {
  const drafts = modules.map(x => x.json).filter(m => m.status === 'draft');
  fs.mkdirSync(outDir, { recursive: true });
  const rows = drafts.map(m => {
    fs.writeFileSync(path.join(outDir, `${m.id}.md`), modulePage(m));
    const unresolved = (m.sources || []).filter(s => UNRESOLVED.test(s.url)).length;
    return { id: m.id, title: m.title, domain: m.domain, todos: collectTodos(m).length, sources: (m.sources || []).length, unresolved };
  });
  const idx = ['# Reviewer sign-off packets', '', 'Generated by `npm run packets`. One page per drafted module. Nothing is approved.', '',
    '| Module | Domain | Sources | Unresolved sources | Open TODOs |', '|--------|--------|---------|--------------------|------------|',
    ...rows.map(r => `| [${r.title}](${r.id}.md) | ${r.domain} | ${r.sources} | ${r.unresolved} | ${r.todos} |`), ''];
  fs.writeFileSync(path.join(outDir, 'INDEX.md'), idx.join('\n'));
  return rows;
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop())) {
  const rows = buildPackets(path.join(ROOT, 'docs', 'signoff'));
  console.log(`signoff-packet: ${rows.length} draft modules written to docs/signoff/`);
}
